##
## EPITECH PROJECT, 2023
## B-MAT-400-MPL-4-1-202unsold-lysandra.manuguerra
## File description:
## Makefile
##

BIN =	202unsold

all :
		cp 202unsold.py 202unsold
		chmod +x 202unsold

clean :

fclean : rm -rf $(BIN)

re : fclean all