##
## EPITECH PROJECT, 2023
## B-MAT-400-MPL-4-1-203hotline-lysandra.manuguerra
## File description:
## Makefile
##

BIN =	203hotline

all :
		cp 203hotline.py 203hotline
		chmod +x 203hotline

clean :

fclean : rm -rf $(BIN)

re : fclean all