##
## EPITECH PROJECT, 2023
## B-MAT-400-MPL-4-1-207demography-lysandra.manuguerra
## File description:
## Makefile
##

BIN =	207demography

all :
		cp 207demography.py 207demography
		chmod +x 207demography

clean :

fclean : rm -rf $(BIN)

re : fclean all