##
## EPITECH PROJECT, 2023
## B-MAT-400-MPL-4-1-205IQ-lysandra.manuguerra
## File description:
## Makefile
##

BIN =	205IQ

all :
		cp 205IQ.py 205IQ
		chmod +x 205IQ

clean :

fclean : rm -rf $(BIN)

re : fclean all