##
## EPITECH PROJECT, 2023
## B-MAT-400-MPL-4-1-209poll-lysandra.manuguerra
## File description:
## Makefile
##

BIN =	209poll

all :
		cp 209poll.py 209poll
		chmod +x 209poll

clean :

fclean : rm -rf $(BIN)

re : fclean all