##
## EPITECH PROJECT, 2023
## B-MAT-400-MPL-4-1-205IQ-lysandra.manuguerra
## File description:
## Makefile
##

BIN =	206neutrinos

all :
		cp 206neutrinos.py 206neutrinos
		chmod +x 206neutrinos

clean :

fclean : rm -rf $(BIN)

re : fclean all