##
## EPITECH PROJECT, 2023
## B-MAT-400-MPL-4-1-208dowels-lysandra.manuguerra
## File description:
## Makefile
##

BIN =	208dowels

all :
		cp 208dowels.py 208dowels
		chmod +x 208dowels

clean :

fclean : rm -rf $(BIN)

re : fclean all