##
## EPITECH PROJECT, 2023
## B-MAT-400-MPL-4-1-204ducks-lysandra.manuguerra
## File description:
## Makefile
##

BIN =	204ducks

all :
		cp 204ducks.py 204ducks
		chmod +x 204ducks

clean :

fclean : rm -rf $(BIN)

re : fclean all