##
## EPITECH PROJECT, 2023
## B-MAT-400-MPL-4-1-201yams-lysandra.manuguerra
## File description:
## Makefile
##

BIN =	201yams

all :
		cp 201yams.py 201yams
		chmod +x 201yams

clean :

fclean : rm -rf $(BIN)

re : fclean all